### PR TITLE
Add evalcs command

### PR DESCRIPTION
**Pull request by DemoJameson**
For easy to execute some simple codes

### CODE REVIEW

**Comment by rhelmot** [comment]
What is the purpose of CorrectArgs? Why are you performing modifications in a hook instead of in the command function?

**Comment by DemoJameson** [comment]
you are right the hook is unnecessary
the `CorrectArgs` method is used to restore the arg, without it the `evalcs var a = 1` is same as `evalcs var`, since space and comma are separators

**Comment by rhelmot** [comment]
Oh, I understand the problem you're trying to work around now. Thank you for your explanation!

This is a good change, I will gladly merge it. Thank you!

**Comment by rhelmot** [comment]
I've uploaded a new release, 0.2.3, which contains this change.

**Pull request merged**
